// Code generated by ent, DO NOT EDIT.

package proxysource

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldDeletedAt, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldOwnerUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldName, v))
}

// SubscriptionURL applies equality check predicate on the "subscription_url" field. It's identical to SubscriptionURLEQ.
func SubscriptionURL(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldSubscriptionURL, v))
}

// RefreshIntervalMinutes applies equality check predicate on the "refresh_interval_minutes" field. It's identical to RefreshIntervalMinutesEQ.
func RefreshIntervalMinutes(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldRefreshIntervalMinutes, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncStatus applies equality check predicate on the "last_sync_status" field. It's identical to LastSyncStatusEQ.
func LastSyncStatus(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldLastSyncStatus, v))
}

// LastSyncError applies equality check predicate on the "last_sync_error" field. It's identical to LastSyncErrorEQ.
func LastSyncError(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldLastSyncError, v))
}

// LastImportedCount applies equality check predicate on the "last_imported_count" field. It's identical to LastImportedCountEQ.
func LastImportedCount(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldLastImportedCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotNull(FieldDeletedAt))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v int64) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLTE(FieldOwnerUserID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldContainsFold(FieldName, v))
}

// SubscriptionURLEQ applies the EQ predicate on the "subscription_url" field.
func SubscriptionURLEQ(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldSubscriptionURL, v))
}

// SubscriptionURLNEQ applies the NEQ predicate on the "subscription_url" field.
func SubscriptionURLNEQ(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNEQ(FieldSubscriptionURL, v))
}

// SubscriptionURLIn applies the In predicate on the "subscription_url" field.
func SubscriptionURLIn(vs ...string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIn(FieldSubscriptionURL, vs...))
}

// SubscriptionURLNotIn applies the NotIn predicate on the "subscription_url" field.
func SubscriptionURLNotIn(vs ...string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotIn(FieldSubscriptionURL, vs...))
}

// SubscriptionURLGT applies the GT predicate on the "subscription_url" field.
func SubscriptionURLGT(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGT(FieldSubscriptionURL, v))
}

// SubscriptionURLGTE applies the GTE predicate on the "subscription_url" field.
func SubscriptionURLGTE(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGTE(FieldSubscriptionURL, v))
}

// SubscriptionURLLT applies the LT predicate on the "subscription_url" field.
func SubscriptionURLLT(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLT(FieldSubscriptionURL, v))
}

// SubscriptionURLLTE applies the LTE predicate on the "subscription_url" field.
func SubscriptionURLLTE(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLTE(FieldSubscriptionURL, v))
}

// SubscriptionURLContains applies the Contains predicate on the "subscription_url" field.
func SubscriptionURLContains(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldContains(FieldSubscriptionURL, v))
}

// SubscriptionURLHasPrefix applies the HasPrefix predicate on the "subscription_url" field.
func SubscriptionURLHasPrefix(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldHasPrefix(FieldSubscriptionURL, v))
}

// SubscriptionURLHasSuffix applies the HasSuffix predicate on the "subscription_url" field.
func SubscriptionURLHasSuffix(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldHasSuffix(FieldSubscriptionURL, v))
}

// SubscriptionURLEqualFold applies the EqualFold predicate on the "subscription_url" field.
func SubscriptionURLEqualFold(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEqualFold(FieldSubscriptionURL, v))
}

// SubscriptionURLContainsFold applies the ContainsFold predicate on the "subscription_url" field.
func SubscriptionURLContainsFold(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldContainsFold(FieldSubscriptionURL, v))
}

// RefreshIntervalMinutesEQ applies the EQ predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesEQ(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesNEQ applies the NEQ predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesNEQ(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNEQ(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesIn applies the In predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesIn(vs ...int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIn(FieldRefreshIntervalMinutes, vs...))
}

// RefreshIntervalMinutesNotIn applies the NotIn predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesNotIn(vs ...int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotIn(FieldRefreshIntervalMinutes, vs...))
}

// RefreshIntervalMinutesGT applies the GT predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesGT(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGT(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesGTE applies the GTE predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesGTE(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGTE(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesLT applies the LT predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesLT(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLT(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesLTE applies the LTE predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesLTE(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLTE(FieldRefreshIntervalMinutes, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotNull(FieldLastSyncedAt))
}

// LastSyncStatusEQ applies the EQ predicate on the "last_sync_status" field.
func LastSyncStatusEQ(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldLastSyncStatus, v))
}

// LastSyncStatusNEQ applies the NEQ predicate on the "last_sync_status" field.
func LastSyncStatusNEQ(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNEQ(FieldLastSyncStatus, v))
}

// LastSyncStatusIn applies the In predicate on the "last_sync_status" field.
func LastSyncStatusIn(vs ...string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIn(FieldLastSyncStatus, vs...))
}

// LastSyncStatusNotIn applies the NotIn predicate on the "last_sync_status" field.
func LastSyncStatusNotIn(vs ...string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotIn(FieldLastSyncStatus, vs...))
}

// LastSyncStatusGT applies the GT predicate on the "last_sync_status" field.
func LastSyncStatusGT(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGT(FieldLastSyncStatus, v))
}

// LastSyncStatusGTE applies the GTE predicate on the "last_sync_status" field.
func LastSyncStatusGTE(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGTE(FieldLastSyncStatus, v))
}

// LastSyncStatusLT applies the LT predicate on the "last_sync_status" field.
func LastSyncStatusLT(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLT(FieldLastSyncStatus, v))
}

// LastSyncStatusLTE applies the LTE predicate on the "last_sync_status" field.
func LastSyncStatusLTE(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLTE(FieldLastSyncStatus, v))
}

// LastSyncStatusContains applies the Contains predicate on the "last_sync_status" field.
func LastSyncStatusContains(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldContains(FieldLastSyncStatus, v))
}

// LastSyncStatusHasPrefix applies the HasPrefix predicate on the "last_sync_status" field.
func LastSyncStatusHasPrefix(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldHasPrefix(FieldLastSyncStatus, v))
}

// LastSyncStatusHasSuffix applies the HasSuffix predicate on the "last_sync_status" field.
func LastSyncStatusHasSuffix(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldHasSuffix(FieldLastSyncStatus, v))
}

// LastSyncStatusEqualFold applies the EqualFold predicate on the "last_sync_status" field.
func LastSyncStatusEqualFold(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEqualFold(FieldLastSyncStatus, v))
}

// LastSyncStatusContainsFold applies the ContainsFold predicate on the "last_sync_status" field.
func LastSyncStatusContainsFold(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldContainsFold(FieldLastSyncStatus, v))
}

// LastSyncErrorEQ applies the EQ predicate on the "last_sync_error" field.
func LastSyncErrorEQ(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldLastSyncError, v))
}

// LastSyncErrorNEQ applies the NEQ predicate on the "last_sync_error" field.
func LastSyncErrorNEQ(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNEQ(FieldLastSyncError, v))
}

// LastSyncErrorIn applies the In predicate on the "last_sync_error" field.
func LastSyncErrorIn(vs ...string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIn(FieldLastSyncError, vs...))
}

// LastSyncErrorNotIn applies the NotIn predicate on the "last_sync_error" field.
func LastSyncErrorNotIn(vs ...string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotIn(FieldLastSyncError, vs...))
}

// LastSyncErrorGT applies the GT predicate on the "last_sync_error" field.
func LastSyncErrorGT(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGT(FieldLastSyncError, v))
}

// LastSyncErrorGTE applies the GTE predicate on the "last_sync_error" field.
func LastSyncErrorGTE(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGTE(FieldLastSyncError, v))
}

// LastSyncErrorLT applies the LT predicate on the "last_sync_error" field.
func LastSyncErrorLT(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLT(FieldLastSyncError, v))
}

// LastSyncErrorLTE applies the LTE predicate on the "last_sync_error" field.
func LastSyncErrorLTE(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLTE(FieldLastSyncError, v))
}

// LastSyncErrorContains applies the Contains predicate on the "last_sync_error" field.
func LastSyncErrorContains(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldContains(FieldLastSyncError, v))
}

// LastSyncErrorHasPrefix applies the HasPrefix predicate on the "last_sync_error" field.
func LastSyncErrorHasPrefix(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldHasPrefix(FieldLastSyncError, v))
}

// LastSyncErrorHasSuffix applies the HasSuffix predicate on the "last_sync_error" field.
func LastSyncErrorHasSuffix(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldHasSuffix(FieldLastSyncError, v))
}

// LastSyncErrorIsNil applies the IsNil predicate on the "last_sync_error" field.
func LastSyncErrorIsNil() predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIsNull(FieldLastSyncError))
}

// LastSyncErrorNotNil applies the NotNil predicate on the "last_sync_error" field.
func LastSyncErrorNotNil() predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotNull(FieldLastSyncError))
}

// LastSyncErrorEqualFold applies the EqualFold predicate on the "last_sync_error" field.
func LastSyncErrorEqualFold(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEqualFold(FieldLastSyncError, v))
}

// LastSyncErrorContainsFold applies the ContainsFold predicate on the "last_sync_error" field.
func LastSyncErrorContainsFold(v string) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldContainsFold(FieldLastSyncError, v))
}

// LastImportedCountEQ applies the EQ predicate on the "last_imported_count" field.
func LastImportedCountEQ(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldEQ(FieldLastImportedCount, v))
}

// LastImportedCountNEQ applies the NEQ predicate on the "last_imported_count" field.
func LastImportedCountNEQ(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNEQ(FieldLastImportedCount, v))
}

// LastImportedCountIn applies the In predicate on the "last_imported_count" field.
func LastImportedCountIn(vs ...int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldIn(FieldLastImportedCount, vs...))
}

// LastImportedCountNotIn applies the NotIn predicate on the "last_imported_count" field.
func LastImportedCountNotIn(vs ...int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldNotIn(FieldLastImportedCount, vs...))
}

// LastImportedCountGT applies the GT predicate on the "last_imported_count" field.
func LastImportedCountGT(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGT(FieldLastImportedCount, v))
}

// LastImportedCountGTE applies the GTE predicate on the "last_imported_count" field.
func LastImportedCountGTE(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldGTE(FieldLastImportedCount, v))
}

// LastImportedCountLT applies the LT predicate on the "last_imported_count" field.
func LastImportedCountLT(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLT(FieldLastImportedCount, v))
}

// LastImportedCountLTE applies the LTE predicate on the "last_imported_count" field.
func LastImportedCountLTE(v int) predicate.ProxySource {
	return predicate.ProxySource(sql.FieldLTE(FieldLastImportedCount, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxySource) predicate.ProxySource {
	return predicate.ProxySource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxySource) predicate.ProxySource {
	return predicate.ProxySource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxySource) predicate.ProxySource {
	return predicate.ProxySource(sql.NotPredicates(p))
}
